### ISSUE TITLE
Install skips resources

### ISSUE THREAD

**Issue by iSentrie** [nertigel/NSAC#1]
First thanks for creating an AC! :)

The issue is when `nsac install all` it skips a lot of resources and after that it kick for those resources it skipped for some reason and those are not in allowed resource list. So kinda weird.

EDIT:
this one throws error on every kick.
SCRIPT ERROR: @NSAC/server.lua:11: attempt to concatenate a nil value
`	print('nsac - detection: '..GetPlayerName(source)..' reason: '..reason)
`

**Comment by nertigel** [comment]
https://github.com/nertigel/NSAC/blob/master/config.lua#L37 for the install issue.

I will take a look at the other issue soon tm.

**Comment by iSentrie** [comment]
![image](https://user-images.githubusercontent.com/29688478/83192953-ee859e80-a13e-11ea-875b-396709d85684.png)
what do you mean by this?

**Comment by nertigel** [comment]
that's before the commit, it's now in https://github.com/nertigel/NSAC/blob/master/config.lua#L58

**Comment by iSentrie** [comment]
Oh.. Now I got it... What if I use both? Will it work if I install for __resource.lua and then change to fxmanifest.lua and install again?

**Comment by nertigel** [comment]
yeah ofc, but if you ever plan on uninstalling you would have to change it again to uninstall from other manifests.
